appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QBGDshCk59CEz5nekH//bvZ/0OySuqQ+iA5/5XSm6TcDFzwqTTTqsHDy27+fB/DWtP7XO+kjJn79AAOP7BXGw+t/izfb+sC7FLqL6Ki26huPUiPBs2VcgvQm+I1eGZ8y/uwHEWFYqizfD+7EH7zjeURZvOneYFT3OLE0E0e5dKq6ibC8IEnFsq7So3H7DKmMIonhZXPZwsEaAGUqlKXpgJMmA81UPjpOZIaTfrFuyACSkX+2vAw4ENVDnWtWFw5mhB8PJSTYQHvf/zEkYXPxvgRTjPmI90BGlLNnZxR+bbzVcy+Ka+wiOLiCiNtu1Q6m2e6/E8P6t9ecq8kLDA2ZlKfC7Nkquvk4n+hJuU4gyL0FO4kVQZY+wYl/2k1ziTYJXMJGVlpbTwabIPE2S8IuDuCBLseYIMznT3ZZ0aMaN16z34JAlYCOgTzMTk7AY19V7GZ4XbImMZiPS8TbaAf3NHAfmg62k/CVKadt96AYjrAp1uqYvQ8cyp/+Y6G4FrraZkxJnb1Rl71z14Wg3fhA3UqUhi2DqdfaYFqGPcOhwXXgQthEfMrR5vLugUF33hNwtjpWpbTZO11/QBO4Ot3fuSi2w3ORYzFObx3FBcDwUbjCeiWk0Rh4+yzvEZvGCoR/BPW/ZUl7eAee0UEUshz1Lm3qkeiX3M6KppsuhEGWdns=}
conda_forge_output_validation: true
