travis:
  secure:
    BINSTAR_TOKEN: oQIURoJPvGPz8uXQPOElLUrYmvXWT/BX0BlJ1vyGdTRpog6mB8kPaYlxxss63ZP7kh/iDUST1mnBL6prFRKCGb+6Yj5RXoXFMtgrTmyCDYb91VUwMQGMSQ1y0EcOKKaAi6KgbobPxb8X7U7oA7Samz3HJYVRkq6AyEmKTKRUTKnkpvNwx6F4+623ZXHoT4oaA1mPgotr233/+CeBB2Ustlf5BbSKqNNrJFo/FFOScQmAA0/A/Bs0GtIlkvUFSBPCUyJEfCREHOZI9AkFf0vyaDErTFwHkq7m9xhllj+YNilpQdjO0to3RMl1m3Wdo2/rM/GxsIaPS4JePHRVphX075JwPUC2ujfVN3YIgn1siIngAk/dlkvOvgJAUF9g80yr8LHyM/FTicuAqlBla9kNRHcb7N32BJtdbL1h2M2Y5slCesBSi+Vtscq9pMeOnCnUMq4QyouoznnWfIsHy8dPGBOfRNtL+dGpwKZ7edJV4scaB7XOomWv4dV46gElQ2SRoF/HBAhL+MmiPkKqduDKi7dR7IQZkpVtLQM+IGyPsHtwp0YpoYzwH4ARb6BUm/p4MyFS6V4+BmklCGNyEYf9gC2PjWvTCgcBByMQ7hde8kfaudBmUIe+8ex1mD4wmXszOwMaUzVAf+QDLGOOpcBGBG68rqwR7716wXfJHbH8aVo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
